### ISSUE TITLE
Add a detail activity.

### ISSUE THREAD

**Issue by Neelabh46** [opencodeiiita/NEWS-Bucket#5]
This open up when an item from list view is created. Show data from the list card tapped here.

**Comment by Cybertron-Avneesh** [comment]
i want to work on it.
i need a clarification that what a detail Activity is going to do.

**Comment by MiKinshu** [comment]
The list view will contain the heading of the news. The detail view will contain the complete news.

**Comment by starboi02** [comment]
sir can i work on this
