### ISSUE TITLE
Add proper title and back button in DetailActivity

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/NEWS-Bucket#52]
1. Add mainactivity as it's parent
2. Add back button
3. Change the title to something relevant

**Comment by Codedude1** [comment]
Claim

**Comment by sarthakm21** [comment]
Claim

**Comment by Rohini13** [comment]
claim

**Comment by sarthakm21** [comment]
@MiKinshu sir, I was the second one to comment after codedude1. Why wasn't this issue assigned to me?

**Comment by MiKinshu** [comment]
You already had 2 issues assigned.

**Comment by sarthakm21** [comment]
Can i claim it now?
