### ISSUE TITLE
Add share button in detail activity

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/NEWS-Bucket#53]
Add a FAB to share the news title from our app.

**Comment by pra1hamesh** [comment]
claim

**Comment by sarthakm21** [comment]
Claim

**Comment by garvitchittora** [comment]
claim

**Comment by blaze-assault** [comment]
Claim it has been inactive

**Comment by sarthakm21** [comment]
@MiKinshu Can I take up this issue now?

**Comment by sarthakm21** [comment]
@shiv07tiwari @MiKinshu Where should the share button take you??

**Comment by shiv07tiwari** [comment]
It shares the detail text using any other feasible app.

**Comment by sarthakm21** [comment]
@shiv07tiwari Sir I added the share button and added a new Intent to it. But the app keeps crashing and I have no idea why. Can you help me out?
This is what I added....
![newfn](https://user-images.githubusercontent.com/58396189/73414837-105c4980-4336-11ea-88c0-e4c3f136586a.PNG)

**Comment by sarthakm21** [comment]
Sir I have done this task too. 
Please merge the pr for back button task and then I'll submit a pr for that task too as I'm having some problems making a branch
